apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cc
  janus-idp.io/tekton: cc
  backstage.io/kubernetes-id: cc
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cc
resources:
- deployment.yaml
- route.yaml
- service.yaml
