apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cc 
  name: cc
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cc 
